### ISSUE TITLE
Issue with line intersection

### ISSUE THREAD

**Issue by fidlip** [aab29/bezier.dart#11]
Given this piece of code:
```
import "package:vector_math/vector_math.dart";
import "package:bezier/bezier.dart";


void main() {

  // try to get intersection of zero axis with bezier -> no luck, intersections are empty
  CubicBezier bezier1 = CubicBezier([Vector2(-214.5, 80.0), Vector2(52.0, 80.0), Vector2(52.0, 530.0), Vector2(214.5, 530.0)]);

  Vector2 start1 = Vector2(0.0, 0.0);
  Vector2 end1 = Vector2(0.0, 1080.0);

  List<double> intersections1 = bezier1.intersectionsWithLineSegment(start1, end1);
  print("bezier1 intersections= $intersections1");

  // now try to translate this situation by 429px to right -> it's OK
  CubicBezier bezier2 = CubicBezier([Vector2(429.0 - 214.5, 80), Vector2(429.0 - 52.0, 80), Vector2(429.0 + 52.0, 530), Vector2(429.0 + 214.5, 530)]);

  Vector2 start2 = Vector2(429, 0);
  Vector2 end2 = Vector2(429, 1080);

  List<double> intersections2 = bezier2.intersectionsWithLineSegment(start2, end2);
  print("bezier2 intersections= $intersections2");

}

```
it's output is:

> bezier1 intersections= []
> bezier2 intersections= [0.4999999999999998]

But both intersections should be the same.

This is how it look like in canvas 429x1080px
![image](https://user-images.githubusercontent.com/6592959/57316683-a7250e00-70f6-11e9-8f65-f8088071b8ab.png)
(it is cropped by canvas)

SDK version 2.1.0
Bezier library version:1.1.1

**Comment by aab29** [comment]
Hey @fidlip !  Thanks a ton for pointing this out!  😮👍 I got a chance to copy/paste and walk through your code snippet myself, and so far I'm thinking you've found a legit bug.  🐞 

I did notice that one of the `52.0` values seems to be subtracted in `bezier2`, whereas it was added in `bezier1`... but I've tried it both ways, and it doesn't seem to make a difference.  I think it should still be finding an intersection for `bezier1`, and it's not.  🙈 

I probably won't have time today to get to the cause of this, but I wanted to thank you and let you know that @IkeBart and I will be looking into it.  🕵  It seems like the value output by `rootsAlongLine` is producing a point that is *just* outside the bounding box of the line segment.  I'm not sure exactly why this might happen.  Possibly an issue with floating point precision?  🦈 We'll also have to check with [Bezier.js](https://github.com/Pomax/bezierjs/blob/17457e1793895aef1f4d8c9f53b7a7c6df55db0c/lib/bezier.js#L786) to see if @Pomax 's library has the same issue, or if we introduced it.  ➰ I have a feeling it was something I messed up.  😅

**Comment by fidlip** [comment]
Thank a lot for reply. When I tried to debug through library code, I had similar observation... but was not able to prepare some fix to offer you some PR.

**Comment by fidlip** [comment]
I hit another situation:
```
  CubicBezier bezier3 = CubicBezier([Vector2(214.5,630), Vector2(308.25,630), Vector2(368.625,492.5), Vector2(429,355)]);
  List<double> intersections3 = bezier3.intersectionsWithLineSegment(Vector2(0,580), Vector2(430,580));
  print("bezier3 intersections= $intersections3");

  // translate 6px up
  CubicBezier bezier4 = CubicBezier([Vector2(214.5,630 - 6.0), Vector2(308.25,630 - 6.0), Vector2(368.625,492.5 - 6.0), Vector2(429,355 - 6.0)]);
  List<double> intersections4 = bezier4.intersectionsWithLineSegment(Vector2(0,580 - 6.0), Vector2(430,580 - 6.0));
  print("bezier4 intersections= $intersections4");

  // translate 6px down
  CubicBezier bezier5 = CubicBezier([Vector2(214.5,630 + 6.0), Vector2(308.25,630 + 6.0), Vector2(368.625,492.5 + 6.0), Vector2(429,355 + 6.0)]);
  List<double> intersections5 = bezier5.intersectionsWithLineSegment(Vector2(0,580 + 6.0), Vector2(430,580 + 6.0));
  print("bezier5 intersections= $intersections5");
```
will print out:

> bezier3 intersections= []
> bezier4 intersections= [0.37197975112055826]
> bezier5 intersections= [0.37197975112055826]

in case of bezier3 it should be the same intersection as in following cases bezier4 & bezier5

**Comment by aab29** [comment]
Thanks again!  These will make great test cases when we get a chance to sit down and find a fix.  🔧✅

**Comment by fidlip** [comment]
Hi Aaron, is there anything I could help you with to solve this issue?

**Comment by aab29** [comment]
Hey @fidlip !  Sorry for the delay.  ⏳ It was a busy week, and now I'm on a vacation with less down time than anticipated. 🏖  I'll try to take a look at this myself tonight, and if not I'll look at it on the plane tomorrow.  ✈️  It's possible I'll need @IkeBart 's help, and if that's the case we can look at it on Monday or Tuesday.  I'm pretty sure we can track it down ourselves, but PRs are always welcome, and if we're stumped on something, we'll definitely share the issue.  🤓 🤓 👐 Thanks!  😎

**Comment by aab29** [comment]
I think I might know what's going on.  🌵 Like we were saying before, it seems like the points produced by plugging the roots back into the curve are *just* outside the bounding box of the line segment.  🔌 🙅‍♂  They're outside by such a small amount, it could easily be introduced by floating point imprecision.  📌

However, I checked the algorithm against its counterpart in Bezier.js, and I noticed one thing they're doing that is subtly different, but apparently important. ⚠️  When they check to see whether points fall within the bounding box, they're relying on the [`between` function](https://github.com/Pomax/bezierjs/blob/17457e1793895aef1f4d8c9f53b7a7c6df55db0c/lib/utils.js#L193).  😮 And of course, `between` relies on `approximately`, which checks for *approximate* equality--something we're not doing.  🤦‍♂ I'm pretty sure once I add in just a little bit of fuzziness, the failing test cases will pass.  🐻  It seems my suspicions were correct--this *was* something I messed up.  😜  Thanks for helping me find it!  🔍

**Comment by fidlip** [comment]
Oh, you are great dear emoticon guy :) I can't imagine how it could be out
of bounding box - apparently I'm missing something important - it's reason
why I didn't offer some PR with my own fix. Thank you again for solving
this issue!

**Comment by aab29** [comment]
No problem!  I'm glad we were able to track it down.  🕵 🆒 Please check out the [PR](https://github.com/aab29/bezier.dart/pull/12) I already merged and the [new release](https://pub.dev/packages/bezier/versions/1.1.2) I made on Pub and make sure everything is in order. 🆕 If it is, I think we can close this issue. 👍  Cheers!  🍻

**Comment by fidlip** [comment]
Hi Aaron. Thanks a lot. I will check it out in two days and let you know.

**Comment by fidlip** [comment]
Hi, I tested it finally. It seems to be working. Good job! Thank you again!

**Comment by aab29** [comment]
Awesome!  😎  You're very welcome.  Thanks for alerting us to the bug!  🐞 🔨
