### ISSUE TITLE
Null Safety Support

### ISSUE THREAD

**Issue by fzyzcjy** [aab29/bezier.dart#19]
Hi looking forward to support null safety! Since flutter has make null safety **stable** today!

**Comment by joshgerdes** [comment]
@aab29 any ETA on when this can get in?

**Comment by aab29** [comment]
Yes!  🙏 So sorry for the delay on this!  I've been pretty tied up with work lately.  I see that @fzyzcjy has submitted https://github.com/aab29/bezier.dart/pull/20 , and I think it's looking pretty good.  👏  I'd like to go over it in more detail today, and I'm *really* going to try my best to get a new release out this weekend.  🤞🤞⏲️
